apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: cilium-vxlan
  name: cilium-vxlan
spec:
  selector:
    matchLabels:
      app: cilium-vxlan
  template:
    metadata:
      labels:
        app: cilium-vxlan
    spec:
      containers:
      - image: burlyluo/nettool
        name: nettoolbox
        securityContext:
          privileged: true

---
apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: NodePort
  selector:
    app: cilium-vxlan
  ports:
  - name: cni
    port: 8080
    targetPort: 80
    nodePort: 32000

