apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: calico-bgp
  name: calico-bgp
spec:
  selector:
    matchLabels:
      app: calico-bgp
  template:
    metadata:
      labels:
        app: calico-bgp
    spec:
      containers:
      - image: localhost:5000/nettool
        name: nettoolbox
        securityContext:
          privileged: true

---
apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: NodePort
  selector:
    app: calico-bgp
  ports:
  - name: cni
    port: 8080
    targetPort: 80
    nodePort: 32000

