apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: bgp
  name: bgp
spec:
  selector:
    matchLabels:
      app: bgp
  template:
    metadata:
      labels:
        app: bgp
    spec:
      containers:
      - image: burlyluo/nettool
        name: nettoolbox
        securityContext:
          privileged: true

---
apiVersion: v1
kind: Service
metadata:
  name: serversvc
spec:
  type: NodePort
  selector:
    app: bgp
  ports:
  - name: cni
    port: 8080
    targetPort: 80
    nodePort: 32000

